version: 0.0
os: linux
files:
  - source: /
    destination: /ecomm-express-api
hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 180
      runas: root