apiVersion: v1
kind: Service # A service is an abstraction that defines a logical set of Pods and a policy by which to access them
metadata:
  name: ecomm-express-api # The name of the service
spec:
  selector:
    app: ecomm-express-api # The selector field defines how the service finds which pods to target
  ports:
    - protocol: TCP
      port: 5000 # The port that the service will expose
      targetPort: 5000  # The port on the container that the service should forward to
  type: LoadBalancer